// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfrwtUNnoH9Oq6U4BbNY0GipofOb4Pt-Y',
    appId: '1:160287224671:web:55fce266cdfb70e557fcea',
    messagingSenderId: '160287224671',
    projectId: 'bitkim-f70ae',
    authDomain: 'bitkim-f70ae.firebaseapp.com',
    storageBucket: 'bitkim-f70ae.appspot.com',
    measurementId: 'G-3TDM5Q7SWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYBn-gIA9JbFQj-Y-QqZF7TN5evrEylQA',
    appId: '1:160287224671:android:b67a24e1aadfe20a57fcea',
    messagingSenderId: '160287224671',
    projectId: 'bitkim-f70ae',
    storageBucket: 'bitkim-f70ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRIsZyJ5BtMI0DVp9nGXBAVSEWI9j8vbE',
    appId: '1:160287224671:ios:226d4a26bc3a0a4a57fcea',
    messagingSenderId: '160287224671',
    projectId: 'bitkim-f70ae',
    storageBucket: 'bitkim-f70ae.appspot.com',
    iosClientId: '160287224671-3et55f3vm2noa1rp08v5tomq92utvcjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitkim',
  );
}
